(function() {
'use strict';
	
angular.module('app.core')
	.constant('GlobalConstantsCore', {
	
		APP_TITLE : "RFDS",
		/******Global variable for Toast mode*****/
		TAOST_TYPE_SUCCESS : "success",
		TAOST_TYPE_WARNING : "warning",
		TAOST_TYPE_ERROR : "error",
		TAOST_TYPE_INFO : "info",
		
		ROW_PER_PAGE_LIMIT : [10,50,100,250,500],
		DATE_FORMAT :[{ TOSHOW : 'MM/DD/YY', ACTUAL : 'mmddyy_slash' },
					 {TOSHOW : 'MM/DD/YYYY', ACTUAL : 'mmddyyyy_slash' },
					 {TOSHOW : 'YY/MM/DD', ACTUAL : 'yymmdd_slash' },
					 {TOSHOW : 'YYYY-MM-DD', ACTUAL : 'yyyymmdd_dash' },
					 {TOSHOW : 'DD-MM-YYYY', ACTUAL : 'ddMMyyyy_dash' },
					 {TOSHOW : 'DD/MM/YY', ACTUAL : 'ddMMyy_slash' },
					 {TOSHOW : 'MM-DD-YYYY', ACTUAL : 'mmddyyyy_dash' },
					 {TOSHOW : 'DD-MMM-YY', ACTUAL : 'ddMMMyy_dash' }
				],
		INITIAL_DATE_FORMAT:'mmddyyyy_dash',
		USERCONFIG_DATE_FORMAT:'MM-DD-YYYY',
		MAX_LIMIT_FOR_PAGINATION:1000,
		MILISECOND_LIMIT_FOR_CLICK_AND_WAIT:3000,
	
		/******User confg *****/
		currentUserConfig  : 'en',
		/******Regular Expressions*****/
		TELEPHONE_REG_EX_CONST : /^[0-9]{10}$/,
		TELEPHONE_REG_EX_CONST_FTR : /^[0-9-]{10,14}$/,
		NAME_REG_EX_CONST : /^[a-zA-Z]+$/,
		USER_NAME_REG_EX_CONST : /^[_\-.A-z0-9]+$/,
		REPORT_NAME_REG_EX_CONST : /^[_\ -.A-z0-9]+$/,
		SAP_ID_LINK_ID_REGEX_CONST : /^[_\-A-z0-9]+$/,
		CHECKSUM_REG_EX_CONST : /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9])/,
		ADDRESS_REG_EX_CONST : /^[-_ /,@&a-zA-Z0-9]+$/,
		MESSAGE_REG_EX_CONST : /^[-_\][%*.`~=|?><}{!#/,'";:$+^  )(@&a-zA-Z0-9]+$/,
		CITY_STATE_REG_EX : /^[A-z -.]+$/,
		STREET_ADDRESS_REG_EX : /\d|[a-zA-Z &-.,/_]{1,60}/,
		ROW_LIMIT_PER_PAGE : [10, 50, 100,250,500],
		INITIAL_LIMIT_PER_PAGE : 10,
		TIME_ZONE_LIST : ['America/Los_Angeles','America/New_York','America/Panama','Asia/Kolkata'],
		INITIAL_TIME_ZONE : "Asia/Kolkata",
		/******Allow pattern expresions*****/
		NUMBER_ALLOW : "(^[0-9]+$)",
		ALPHA_ONLY_ALLOW : "(\d|[a-zA-Z])",
		ALPHA_WITH_SPACE_ALLOW : "(\d|[a-zA-Z ])",
		ALPHA_WITH_SPACE_DOT_AND_HYPHEN_ALLOW : "(\d|[a-zA-Z .-])",
		ALPHA_WITH_SPACE_HYPHEN_ALLOW : "(\d|[a-zA-Z -])",
		ALPHA_WITH_SPACE_DOT_ALLOW : "(\d|[a-zA-Z .])",
		NUMERIC_WITH_DOT_ALLOW : "([0-9.])",
		ALPHA_NUMERIC_ALLOW : "(\d|[a-zA-Z0-9])",
		ALPHA_NUMERIC_SPACE_ALLOW : "(\d|[a-zA-Z0-9 ])",
		ALPHANUMERIC_ALLOW_SPECIAL_ADDRESS : "(^[a-zA-Z0-9()_@ ,#.\'\"/&\-]+$)",
		ALPHANUMERIC_WITH_DOT_HYPHEN_AND_UNDERSCORE : "(^[a-zA-Z0-9_.\-]+$)",
		ALPHANUMERIC_WITH_DOT_HYPHEN_AND_UNDERSCORE_AND_SPACE : "(^[a-zA-Z0-9_.\ -]+$)",
		ALPHANUMERIC_WITH_HYPHEN_AND_UNDERSCORE : "(^[a-zA-Z0-9_\-]+$)",
		ALPHANUMERIC_WITH_DOT_COMMA_AND_BRACKETS : "(^[a-zA-Z0-9.,() ]+$)",
		ALPHANUMERIC_WITH_DOT_COMMA_AND_BRACKETS_AND_HYPHEN :"(^[a-zA-Z0-9.,() -]+$)",
		EMAIL_ALLOW : "(^[a-zA-Z0-9_.@\-]+$)",
		ALPHANUMERIC_WITH_HYPHEN_AND_UNDERSCORE_SPACE: "(^[a-zA-Z0-9_\ -]+$)",
		ALPHANUMERIC_WITH_SINGLE_DOT_AND_UNDERSCORE_SPACE: "(^(?!.*?[._]{2})[a-zA-Z0-9_.]+$)",                
        DEFAULT_FOREIGN_KEY_ULIMIT : 1000,
		DEFAULT_FOREIGN_KEY_LLIMIT : 0,
		DEFAULT_FOREIGN_KEY_ORDER_TYPE : 'asc',
       
       RELATIONSHIP_TYPES :[{ TOSHOW : 'Single', ACTUAL : 'Single' },
					 {TOSHOW : 'In a relationship', ACTUAL : 'In_a_relationship' },
					 {TOSHOW : 'Engaged', ACTUAL : 'Engaged' },
					 {TOSHOW : 'Married', ACTUAL : 'Married' },
					 {TOSHOW : 'complicated', ACTUAL : 'complicated' },
					 {TOSHOW : 'separated', ACTUAL : 'separated' },
					 
				],
       DIET_TYPES :[{ TOSHOW : 'veg', ACTUAL : 'veg' },
					 {TOSHOW : 'nonVeg', ACTUAL : 'nonVeg' },
				],
				
		EDUCATION_LEVEL :[{ TOSHOW : 'Highschool', ACTUAL : 'Highschool' },
					 {TOSHOW : 'Graducation', ACTUAL : 'Graducation' },
					 {TOSHOW : 'Post graducation', ACTUAL : 'Post_graducation' },
					 {TOSHOW : 'None', ACTUAL : 'None' },
				],
		JOBTYPE_LEVEL :[{ TOSHOW : 'Private', ACTUAL : 'Private' },
					 {TOSHOW : 'Government', ACTUAL : 'Government' },
					 {TOSHOW : 'Business', ACTUAL : 'Business' },
					 {TOSHOW : 'None', ACTUAL : 'None' },
				],
				
		DEITY_TYPES :[{ name : 'Revaya', id : '1' },
					 {name : 'Gavaya', id : '2' },
					 {name : 'Naganya', id : '3' },
					 {name : 'Bablaja', id : '4' },
					 {name : 'Tivdaja', id : '5' },
					 {name : 'Bairaja', id : '6' },
					 {name : 'Saatmata', id : '7' },
					 {name : 'Chhaiymanya', id : '8' },
					 {name : 'kundlaja', id : '9' },
					 {name : 'Nareshwari', id : '10' },
					 {name : 'Nandeshwari', id : '11' },
				],		
				
		GOUTRA_TYPES :[{ name : "kashyap", id : '1' },
			{ name : "Kouravya", id : '2' },
			{ name : "Goutam", id : '3' },
			{ name : "Bhardwa", id : '4' },
			{ name : "Madvya", id : '5' },
			{ name : "Parashar", id : '6' },
			{ name : "koushal", id : '7' },
			{ name : "Garg", id : '8' },
			{ name : "Dhananjay", id : '9' },
			{ name : "Kurve", id : '10' },
			{ name : "Vaishya", id : '11' },
			{ name : "Nagar", id : '12' },
			{ name : "Bhargav", id : '13' },
			{ name : "Kodavya", id : '14' },
			{ name : "Kapil", id : '15' },
			{ name : "Nandiyana", id : '16' },
			{ name : "Markandeyy", id : '17' },
			{ name : "Mandavi", id : '18' },
		],	
		
				
		
});

})();
